/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import Model.ClienteModel;
import Model.DAO.ConexaoBD;
import Model.PfisicaModel;
import Model.PjuridicaModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author innanplinio
 */
public class AlterarClienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form AlterarClienteFrame
     */
    public AlterarClienteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        cartao = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        cep = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        conta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comp = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        clienteBox = new javax.swing.JComboBox<>();
        Fisica = new javax.swing.JRadioButton();
        Juridica = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Cliente");

        nome.setText("Nome");
        nome.setPreferredSize(new java.awt.Dimension(150, 20));

        cartao.setText("Cartão");
        cartao.setPreferredSize(new java.awt.Dimension(150, 20));

        num.setText("Num");
        num.setPreferredSize(new java.awt.Dimension(150, 20));

        cep.setText("CEP");
        cep.setPreferredSize(new java.awt.Dimension(150, 20));

        tel.setText("Telefone");
        tel.setPreferredSize(new java.awt.Dimension(150, 20));

        Cadastrar.setText("Cadastrar");
        Cadastrar.setPreferredSize(new java.awt.Dimension(120, 32));
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        conta.setText("Conta");
        conta.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel1.setText("Informações Basicas");

        comp.setText("Complemento");
        comp.setPreferredSize(new java.awt.Dimension(150, 20));

        cpf.setText("CPF ou CNPJ");
        cpf.setPreferredSize(new java.awt.Dimension(150, 20));

        clienteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID CLIENTE" }));
        clienteBox.setBorder(null);
        clienteBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        this.populaComboBox();
        clienteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteBoxActionPerformed(evt);
            }
        });

        Fisica.setText("Pessoa Fisica");

        Juridica.setText("Pessoa Juridica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(conta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cartao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Juridica))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fisica)
                            .addComponent(Juridica))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addComponent(cpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(conta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cartao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addComponent(Cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        onClickCadastrar();
    }//GEN-LAST:event_CadastrarActionPerformed

    void onClickCadastrar(){
        ClienteModel c = new ClienteModel();
        c.setIdCliente(Integer.parseInt(clienteBox.getSelectedItem().toString()));
        c.setNome(nome.getText());
        c.setTelefone(tel.getText());
        c.setCep(cep.getText());
        c.setComplemento(comp.getText());
        c.setNumCartao(cartao.getText());
        c.setNumConta(conta.getText());
        c.setNumero(num.getText());
        c.save(); 
        if(Fisica.isSelected()){
            PfisicaModel f = new PfisicaModel();
            f.setCpf(cpf.getText());
            f.save();
        }else if(Juridica.isSelected()){
            PjuridicaModel j = new PjuridicaModel();
            j.setCnpj(cpf.getText());
            j.save();
        }
             
    }
    
    
    private void clienteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteBoxActionPerformed
        Fisica.setSelected(false);
        Juridica.setSelected(false);
        if(clienteBox.getSelectedIndex() != -1){
            int id = Integer.parseInt(clienteBox.getSelectedItem().toString());
            ClienteModel c = ClienteModel.get(id);
            PfisicaModel f = PfisicaModel.get(id);
            PjuridicaModel j = PjuridicaModel.get(id);
            if(f != null){
                cpf.setText(f.getCpf());
                Fisica.setSelected(true);
            }else{
                cpf.setText(j.getCnpj());
                Juridica.setSelected(true);
            }
            nome.setText(c.getNome());
            cep.setText(c.getCep());
            comp.setText(c.getComplemento());
            tel.setText(c.getTelefone());
            num.setText(c.getNumero());
            conta.setText(c.getNumConta());
            cartao.setText(c.getNumCartao());            
        }
    }//GEN-LAST:event_clienteBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            } catch (InstantiationException ex) {     } catch (IllegalAccessException ex) {
               } catch (javax.swing.UnsupportedLookAndFeelException ex) {       }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarClienteFrame().setVisible(true);
            }
        });
    }
    
    private void populaComboBox() {
try{
    PreparedStatement ps = ConexaoBD.getConexaoBD().prepareStatement("SELECT IdCliente   FROM Cliente ");     
        ResultSet rs = ps.executeQuery();
        while(rs.next())
        {
            clienteBox.addItem(rs.getString("IdCliente"));
            
        }
}catch(SQLException ex){
   JOptionPane.showMessageDialog(null, ex);
}
        
       
       
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JRadioButton Fisica;
    private javax.swing.JRadioButton Juridica;
    private javax.swing.JTextField cartao;
    private javax.swing.JTextField cep;
    private javax.swing.JComboBox<String> clienteBox;
    private javax.swing.JTextField comp;
    private javax.swing.JTextField conta;
    private javax.swing.JTextField cpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField num;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
