/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import Model.AluguelModel;
import Model.ClienteModel;
import Model.DAO.ConexaoBD;
import Model.PaluguelModel;
import Model.PvendaModel;
import Model.RevisaoModel;
import Model.VeiculoModel;
import Model.VendedorModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author innanplinio
 */
public class AlugarVeiculoFrame extends javax.swing.JFrame {

    /**
     * Creates new form AlugarVeiculoFrame
     */
    public AlugarVeiculoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteBox = new javax.swing.JComboBox<>();
        funcionarioBox = new javax.swing.JComboBox<>();
        carroBox = new javax.swing.JComboBox<>();
        data = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        valorMulta = new javax.swing.JTextField();
        dataDevolucao = new javax.swing.JTextField();
        Finalizar = new javax.swing.JButton();
        fim = new javax.swing.JRadioButton();
        km = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alugar Veiculo");

        clienteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));

        funcionarioBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario" }));

        carroBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro" }));
        this.populaComboBox();

        data.setText("Data");
        data.setPreferredSize(new java.awt.Dimension(150, 20));

        valor.setText("Valor");
        valor.setPreferredSize(new java.awt.Dimension(150, 20));

        valorMulta.setText("Valor Multa");
        valorMulta.setPreferredSize(new java.awt.Dimension(150, 20));

        dataDevolucao.setText("Data Devolução");
        dataDevolucao.setPreferredSize(new java.awt.Dimension(150, 20));

        Finalizar.setText("Finalizar");
        Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarActionPerformed(evt);
            }
        });

        fim.setText("Finalizado");

        km.setText("KM Rodado");
        km.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fim)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(carroBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clienteBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dataDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valorMulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(km, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(122, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(funcionarioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funcionarioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(km, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarActionPerformed
        try {
            onClickFinalizar();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_FinalizarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
        } catch (InstantiationException ex) {
                   } catch (IllegalAccessException ex) {
                 } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlugarVeiculoFrame().setVisible(true);
            }
        });
    }
    void onClickFinalizar() throws SQLException{
        AluguelModel a = new AluguelModel();
        a.setCliente(ClienteModel.get(Integer.parseInt(clienteBox.getSelectedItem().toString())));
        a.setVeiculo(PaluguelModel.get(Integer.parseInt(carroBox.getSelectedItem().toString())));
        a.setVendedor(VendedorModel.get(funcionarioBox.getSelectedItem().toString()));
        a.setDataInicio(data.getText());
        a.setDataFim(dataDevolucao.getText());
        if(fim.isSelected())
            a.setFinalizado(1);
        else a.setFinalizado(0);
        a.setMultaAtraso(Float.parseFloat(valorMulta.getText()));
        a.setValorTotal(Float.parseFloat(valor.getText()) + Float.parseFloat(valorMulta.getText()));
        a.setKmRodados(Integer.parseInt(km.getText()));
        PreparedStatement ps1 = ConexaoBD.getConexaoBD().prepareStatement("SELECT IdRevisao FROM Revisao WHERE idVeiculo = ? ");
        ps1.setInt(1, a.getVeiculo().getIdVeiculo());
        ResultSet rs1 = ps1.executeQuery();
        while(rs1.next()){
            String t = rs1.getString(1);
            a.setRevisao(RevisaoModel.get(Integer.parseInt(t)));
        }
        PreparedStatement ps2 = ConexaoBD.getConexaoBD().prepareStatement("UPDATE Veiculo SET situacao = 2 WHERE idVeiculo = ?");
        ps2.setString(1, carroBox.getSelectedItem().toString());
        ps2.execute();    
        a.save();
    }
    
    private void populaComboBox() {

        try {

            PreparedStatement ps1 = ConexaoBD.getConexaoBD().prepareStatement("SELECT IdCliente FROM Cliente ");
            ResultSet rs1 = ps1.executeQuery();
            PreparedStatement ps2 = ConexaoBD.getConexaoBD().prepareStatement("SELECT CpfFuncionario FROM Vendedor ");
            ResultSet rs2 = ps2.executeQuery();
            PreparedStatement ps3 = ConexaoBD.getConexaoBD().prepareStatement("SELECT idVeiculo FROM Veiculo WHERE Situacao =1");
            ResultSet rs3 = ps3.executeQuery();

            while (rs2.next()) {
                funcionarioBox.addItem(rs2.getString("CpfFuncionario"));
            }
            while (rs1.next()) {
                clienteBox.addItem(rs1.getString("IdCliente"));
            }
            while (rs3.next()) {
                carroBox.addItem(rs3.getString("IdVeiculo"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Finalizar;
    private javax.swing.JComboBox<String> carroBox;
    private javax.swing.JComboBox<String> clienteBox;
    private javax.swing.JTextField data;
    private javax.swing.JTextField dataDevolucao;
    private javax.swing.JRadioButton fim;
    private javax.swing.JComboBox<String> funcionarioBox;
    private javax.swing.JTextField km;
    private javax.swing.JTextField valor;
    private javax.swing.JTextField valorMulta;
    // End of variables declaration//GEN-END:variables
}
