/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import Model.ClienteModel;
import Model.DAO.ConexaoBD;
import Model.MecanicoModel;
import Model.RevisaoModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author innanplinio
 */
public class ConsultarRevisaoFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarRevisaoFrame
     */
    public ConsultarRevisaoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idRevisaoBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        mecanico = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        situacao = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        veiculo = new javax.swing.JTextField();
        valorR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idRevisaoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Revisao" }));
        idRevisaoBox.setBorder(null);
        this.populaComboBox();
        idRevisaoBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idRevisaoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRevisaoBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar Revisão");

        cliente.setText("Cliente");
        cliente.setPreferredSize(new java.awt.Dimension(150, 20));

        mecanico.setText("Mecânico");
        mecanico.setPreferredSize(new java.awt.Dimension(150, 20));

        data.setText("Data de Devolução (Data)");
        data.setPreferredSize(new java.awt.Dimension(150, 20));

        situacao.setText("Situação");
        situacao.setPreferredSize(new java.awt.Dimension(150, 20));

        valor.setText("Valor Conserto");
        valor.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel3.setText("Informações do Veiculo");

        veiculo.setText("Veiculo");
        veiculo.setPreferredSize(new java.awt.Dimension(150, 20));

        valorR.setText("Valor Revisao");
        valorR.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idRevisaoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(valorR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idRevisaoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idRevisaoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRevisaoBoxActionPerformed
        onClickidRevisaoBox();
    }//GEN-LAST:event_idRevisaoBoxActionPerformed

    void onClickidRevisaoBox(){
        RevisaoModel r = RevisaoModel.get(Integer.parseInt(idRevisaoBox.getSelectedItem().toString()));
        cliente.setText(ClienteModel.get(r.getCliente().getIdCliente()).getNome());
        mecanico.setText(r.getMecanico().getCpfFuncionario());
        veiculo.setText("" + r.getVeiculo().getIdVeiculo());
        data.setText(r.getDataRevisao());
        if(r.isEfetivado()){
            situacao.setText("REVISADO");
        }else{
            situacao.setText("NAO REVISAO");
        }
        valor.setText("" + r.getValorConserto());
        valorR.setText(""+r.getValorRevisao());
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
         } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarRevisaoFrame().setVisible(true);
            }
        });
    }
    
    private void populaComboBox() {
        try{
            PreparedStatement ps = ConexaoBD.getConexaoBD().prepareStatement("SELECT idRevisao FROM Revisao ");     
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    idRevisaoBox.addItem(rs.getString("IdRevisao"));
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField data;
    private javax.swing.JComboBox<String> idRevisaoBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mecanico;
    private javax.swing.JTextField situacao;
    private javax.swing.JTextField valor;
    private javax.swing.JTextField valorR;
    private javax.swing.JTextField veiculo;
    // End of variables declaration//GEN-END:variables
}
