/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import Model.ClienteModel;
import Model.DAO.ConexaoBD;
import Model.MecanicoModel;
import Model.RevisaoModel;
import Model.VeiculoModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author innanplinio
 */
public class NovaRevisaoFrame extends javax.swing.JFrame {

    /**
     * Creates new form NovaRevisaoFrame
     */
    public NovaRevisaoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteBox = new javax.swing.JComboBox<>();
        data = new javax.swing.JTextField();
        mecanicoBox = new javax.swing.JComboBox<>();
        carroBox = new javax.swing.JComboBox<>();
        valor = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        valorConserto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clienteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));
        clienteBox.setBorder(null);
        this.populaComboBoxCliente();
        clienteBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        data.setText("Data de Entrada");
        data.setPreferredSize(new java.awt.Dimension(150, 20));

        mecanicoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecânico" }));
        mecanicoBox.setBorder(null);
        this.populaComboBoxMecanico();
        mecanicoBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        carroBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro" }));
        carroBox.setBorder(null);
        this.populaComboBoxCarro();
        carroBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        valor.setText("Valor Revisao");
        valor.setPreferredSize(new java.awt.Dimension(150, 20));

        Cadastrar.setText("Concretizar Revisão");
        Cadastrar.setPreferredSize(new java.awt.Dimension(150, 32));
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        valorConserto.setText("Valor Conserto");
        valorConserto.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mecanicoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorConserto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mecanicoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorConserto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        onClickCadastrar();
    }//GEN-LAST:event_CadastrarActionPerformed

    void onClickCadastrar(){
        RevisaoModel r = new RevisaoModel();
        //r.setIdRevisao(0);
        r.setCliente(ClienteModel.get(Integer.parseInt(clienteBox.getSelectedItem().toString())));
        r.setDataRevisao(data.getText());
        r.setEfetivado(true);
        r.setMecanico(MecanicoModel.get(mecanicoBox.getSelectedItem().toString()));
        r.getMecanico().setCpfFuncionario(mecanicoBox.getSelectedItem().toString());
        r.setValorConserto(Float.parseFloat(valorConserto.getText()));
        r.setValorRevisao(Float.parseFloat(valor.getText()));
        r.setVeiculo(VeiculoModel.get(Integer.parseInt(carroBox.getSelectedItem().toString())));
       
        r.save();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaRevisaoFrame().setVisible(true);
            }
        });
    }
    
    private void populaComboBoxCliente() {
        try{
            PreparedStatement ps = ConexaoBD.getConexaoBD().prepareStatement("SELECT IdCliente FROM Cliente ");     
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    clienteBox.addItem(rs.getString("IdCliente"));
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
    }
    private void populaComboBoxMecanico() {
        try{
            PreparedStatement ps = ConexaoBD.getConexaoBD().prepareStatement("SELECT cpfFuncionario FROM Mecanico ");     
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    mecanicoBox.addItem(rs.getString("cpfFuncionario"));
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
    }
    private void populaComboBoxCarro() {
        try{
            PreparedStatement ps = ConexaoBD.getConexaoBD().prepareStatement("SELECT idVeiculo FROM Veiculo ");     
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    carroBox.addItem(rs.getString("IdVeiculo"));
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JComboBox<String> carroBox;
    private javax.swing.JComboBox<String> clienteBox;
    private javax.swing.JTextField data;
    private javax.swing.JComboBox<String> mecanicoBox;
    private javax.swing.JTextField valor;
    private javax.swing.JTextField valorConserto;
    // End of variables declaration//GEN-END:variables
}
